### ISSUE TITLE
Is that possible to share the training dataset : CMU Panoptic Dataset ?

### ISSUE THREAD

**Issue by weilidldnl** [Ascend-Research/HeadPoseEstimation-WHENet#13]

**Comment by lucaskyle** [comment]
too big i think  
plz use their panoptic panoptic-toolbox
u better check  prepare_image.py

**Comment by weilidldnl** [comment]
> too big i think
> plz use their panoptic panoptic-toolbox
> u better check prepare_image.py

thanks

**Comment by lucaskyle** [comment]
also, u can change the parameters for saving images from  HD videos using prepare_image.py

like the interval of the frame number and angle threshold of changes to save.
i think they just spent much time doing some data cleaning. 
i found some data not good, especially in the haggling datasets.
